# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\3.Terminal\terminal.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 547, 446))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.monitor = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.monitor.setObjectName("monitor")
        self.gridLayout_4.addWidget(self.monitor, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 2, 1)
        self.settingsBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsBox.sizePolicy().hasHeightForWidth())
        self.settingsBox.setSizePolicy(sizePolicy)
        self.settingsBox.setObjectName("settingsBox")
        self.gridLayout = QtWidgets.QGridLayout(self.settingsBox)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.serialPortLabel = QtWidgets.QLabel(self.settingsBox)
        self.serialPortLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.serialPortLabel.setObjectName("serialPortLabel")
        self.gridLayout.addWidget(self.serialPortLabel, 0, 1, 1, 1)
        self.baudRateLabel = QtWidgets.QLabel(self.settingsBox)
        self.baudRateLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.baudRateLabel.setObjectName("baudRateLabel")
        self.gridLayout.addWidget(self.baudRateLabel, 1, 1, 1, 1)
        self.baudRateComboBox = QtWidgets.QComboBox(self.settingsBox)
        self.baudRateComboBox.setObjectName("baudRateComboBox")
        self.gridLayout.addWidget(self.baudRateComboBox, 1, 2, 1, 1)
        self.serialPortComboBox = QtWidgets.QComboBox(self.settingsBox)
        self.serialPortComboBox.setObjectName("serialPortComboBox")
        self.gridLayout.addWidget(self.serialPortComboBox, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.applyPushButton = QtWidgets.QPushButton(self.settingsBox)
        self.applyPushButton.setEnabled(True)
        self.applyPushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.applyPushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.applyPushButton.setAutoFillBackground(False)
        self.applyPushButton.setAutoDefault(False)
        self.applyPushButton.setObjectName("applyPushButton")
        self.gridLayout.addWidget(self.applyPushButton, 2, 2, 1, 1)
        self.gridLayout_3.addWidget(self.settingsBox, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sendLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.sendLineEdit.setObjectName("sendLineEdit")
        self.horizontalLayout.addWidget(self.sendLineEdit)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout_3.addWidget(self.groupBox_2, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(False)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtWidgets.QMenu(self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionDisconnct = QtWidgets.QAction(MainWindow)
        self.actionDisconnct.setObjectName("actionDisconnct")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFIle.addAction(self.actionConnect)
        self.menuFIle.addAction(self.actionDisconnct)
        self.menuFIle.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFIle.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Monitor"))
        self.settingsBox.setTitle(_translate("MainWindow", "Settings"))
        self.serialPortLabel.setText(_translate("MainWindow", "Serial Port"))
        self.baudRateLabel.setText(_translate("MainWindow", "Baud Rate"))
        self.applyPushButton.setText(_translate("MainWindow", "Apply"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Send Box"))
        self.pushButton.setText(_translate("MainWindow", "Send"))
        self.menuFIle.setTitle(_translate("MainWindow", "FIle"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionDisconnct.setText(_translate("MainWindow", "Disconnct"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
